import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Tables } from "@/integrations/supabase/types";
import { fmtKES } from "./finance";
import { loanOutstanding } from "./balance";

type Loan = Tables<"loans">;

const PERIOD_LABEL: Record<string, string> = {
  DAILY: "per day",
  WEEKLY: "per week",
  MONTHLY: "per month",
  YEARLY: "per year",
};

export function defaultReminderMessage(name: string): string {
  return `Hi ${name || "there"}, this is a friendly reminder about the loan we agreed on. Whenever you're able, kindly settle the outstanding amount using the payment details below. Thank you for your honesty and cooperation — it means a lot.`;
}

export function exportLoanReportPDF(loan: Loan, opts?: { lenderName?: string }) {
  if (typeof window === "undefined") throw new Error("PDF only in browser");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const period = (loan as unknown as { interest_period?: string }).interest_period ?? "MONTHLY";
  const payable = loanOutstanding(loan);
  const contactPhone = (loan as unknown as { contact_phone?: string }).contact_phone ?? "";
  const contactEmail = (loan as unknown as { contact_email?: string }).contact_email ?? "";
  const contactAlt = (loan as unknown as { contact_alt?: string }).contact_alt ?? "";
  const payInstr = (loan as unknown as { payment_instructions?: string }).payment_instructions ?? "";
  const message = (loan as unknown as { reminder_message?: string }).reminder_message ?? defaultReminderMessage(loan.lender);

  // Header band
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, W, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Loan Statement", 40, 42);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Prepared by ${opts?.lenderName ?? "Lender"} · ${new Date().toLocaleDateString()}`, 40, 64);
  doc.setTextColor(15, 23, 42);

  let y = 120;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Loanee details", 40, y);
  autoTable(doc, {
    startY: y + 8,
    body: [
      ["Full name", loan.lender],
      ["Phone", contactPhone || "—"],
      ["Email", contactEmail || "—"],
      ["Alternative contact", contactAlt || "—"],
    ],
    styles: { fontSize: 10, cellPadding: 6 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 160 } },
    margin: { left: 40, right: 40 },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Loan terms", 40, y);
  autoTable(doc, {
    startY: y + 8,
    body: [
      ["Date lent", new Date(loan.borrowed_at).toLocaleDateString()],
      ["Amount lent (principal)", fmtKES(Number(loan.principal))],
      ["Interest rate", `${Number(loan.interest_rate)}% ${PERIOD_LABEL[period] ?? ""}`],
      ["Interest period", period.charAt(0) + period.slice(1).toLowerCase()],
      ["Due date", loan.due_date ? new Date(loan.due_date).toLocaleDateString() : "Open"],
      ["Amount repaid so far", fmtKES(Number(loan.amount_repaid ?? 0))],
      ["Total payable now", fmtKES(payable)],
      ["Purpose", loan.purpose ?? "—"],
    ],
    styles: { fontSize: 10, cellPadding: 6 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 160 } },
    margin: { left: 40, right: 40 },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;

  // Payment details block
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(40, y, W - 80, 90, 8, 8, "FD");
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("How to pay", 56, y + 22);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const payLines = doc.splitTextToSize(payInstr || "Please contact the lender for payment details.", W - 112);
  doc.text(payLines, 56, y + 42);
  y += 110;

  // Personal message
  if (y > 700) { doc.addPage(); y = 48; }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("A note from the lender", 40, y);
  y += 16;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(11);
  const msgLines = doc.splitTextToSize(message, W - 80);
  doc.text(msgLines, 40, y);
  y += msgLines.length * 15 + 20;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by MalinGu · This is a personal statement, not a legal demand.", 40, 800);

  doc.save(`loan-statement-${loan.lender.replace(/\s+/g, "-").toLowerCase()}-${new Date().toISOString().slice(0, 10)}.pdf`);
}